config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  require 'sidekiq/web'
    mount Sidekiq::Web => '/sidekiq'
  devise_for :users

  root 'home#index'

  namespace :admin do
    root 'dashboard#index'
    resources :menu_items
    resources :pages
    resources :news_categories
    resources :news
    resources :app_configurations, only: [:edit, :update]
  end

  resources :pages, path: 'conteudo', only: :show
  resources :contacts, path: 'fale-conosco', only: [:new, :create]

end

app/models/app_configuration.rb
class AppConfiguration < ActiveRecord::Base
  self.table_name = "configurations"
  serialize :definitions

  def self.find_uniq
    app_configuration = AppConfiguration.first
    unless app_configuration
      app_configuration = AppConfiguration.new
      app_configuration.save
    end
    app_configuration
  end

  def company_name
    return I18n.t('app_title') if self.definitions.nil?
    self.definitions['company_name'].blank? ? I18n.t('app_title') : self.definitions['company_name']
  end
end

app/models/ckeditor/asset.rb
class Ckeditor::Asset < ActiveRecord::Base
  include Ckeditor::Orm::ActiveRecord::AssetBase
  include Ckeditor::Backend::Paperclip
end

app/models/contact.rb
class Contact < ActiveRecord::Base
  validates :name, :email, :message, presence: true
  after_create do
    ContactJob.perform_later self
  end
end

app/models/menu_item.rb
class MenuItem < ActiveRecord::Base
  has_closure_tree
  validates :title, presence: true

  def first_link
    return self.link unless self.link.blank?
    self.children.where("link is not null").first.try(:link)
  end
end

app/models/news.rb
class News < ActiveRecord::Base
  extend FriendlyId
  acts_as_taggable
  attr_accessor :master_picture

  friendly_id :title, use: :slugged
  belongs_to :news_category
  has_many :pictures, as: :imageable, dependent: :destroy

  validates :title, :content, :resume, :news_category_id, presence: true

  scope :portal_transparencia, -> {joins(:news_category).where("news_categories.slug = ?", "portal-transparencia")}

  def picture
    @picture ||= begin
      pictures.where(master: true).first.try(:image)
    end
  end

  after_save do
    if self.master_picture
      Picture.transaction do
        self.pictures.update_all(master: false)
        self.pictures.build(master: true, image: self.master_picture).save!
      end
    end
  end
end

app/models/news_category.rb
class NewsCategory < ActiveRecord::Base
  extend FriendlyId
  friendly_id :name, use: :slugged
  validates :name, presence: true
  has_many :news, dependent: :destroy
end

app/models/page.rb
class Page < ActiveRecord::Base
  extend FriendlyId
  acts_as_taggable
  attr_accessor :master_picture

  friendly_id :title, use: :slugged
  validates :title, :content, presence: true
  has_many :pictures, as: :imageable, dependent: :destroy

  def picture
    @picture ||= begin
      pictures.where(master: true).first.try(:image)
    end
  end

  after_save do
    if self.master_picture
      Picture.transaction do
        self.pictures.update_all(master: false)
        self.pictures.build(master: true, image: self.master_picture).save!
      end
    end
  end
end

app/models/picture.rb
class Picture < ActiveRecord::Base
  belongs_to :imageable, polymorphic: true
  has_attached_file :image, styles: { front_small_list: '76x76#', front_medium: '600x398#', front_medium_vertical_list: "250x143#", front_horizontal_medium_list: '396x150#', big: '1600x972#' }, default_style: :big
  validates_attachment_content_type :image, content_type: ["image/jpg", "image/jpeg", "image/png", "image/gif"]
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :site_menu_items, :app_configuration

  def site_menu_items
    MenuItem.roots
  end

  def app_configuration
    AppConfiguration.find_uniq
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController

  # GET /contacts/new
  def new
    @contact = Contact.new
  end

  # POST /contacts
  # POST /contacts.json
  def create
    @contact = Contact.new(contact_params)

    respond_to do |format|
      if @contact.save
        format.html { redirect_to root_path, notice: 'Contato feito com sucesso.' }
        format.json { render :show, status: :created, location: @contact }
      else
        format.html { render :new }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  private

    # Never trust parameters from the scary internet, only allow the white list through.
    def contact_params
      params.require(:contact).permit(:name, :email, :message)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @news_portal_transparencias = News.portal_transparencia.where(created_at: Date.today.beginning_of_year..Date.today.end_of_year)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :set_page, only: [:show]


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_page
      @page = Page.friendly.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def in_admin?
    controller.class.name.split("::").first=="Admin"
  end
end

app/helpers/configurations_helper.rb
module ConfigurationsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/home_helper.rb
module HomeHelper
  def portal_transparencias_dates(news)
    news.pluck(:created_at).map{|t| t.to_s(:db)}
  end
end

app/helpers/news_categories_helper.rb
module NewsCategoriesHelper
end

app/helpers/news_helper.rb
module NewsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/admin/pages/_form.html.erb
<%= simple_form_for [:admin, @page], wrapper: :vertical_input_group, :html => { :class => 'vertical-horizontal' } do |f| %>
  <%= f.error_notification %>

  <%= f.input :title %>
  <%= error_span(@page[:title]) %>
  <%= f.input :master_picture, as: :file %>
  <% if f.object.picture %>
  <div class="row form-group">
    <figure><%= image_tag f.object.picture.url(:big), class: "col-lg-6" %></figure>
  </div>
  <% end -%>
  <%= error_span(@page[:master_picture]) %>
  <%= f.input :content, :as => :ckeditor, :input_html => { :ckeditor => {:toolbar => 'Full'} } %>
  <%= error_span(@page[:content]) %>
  <%= f.input :tag_list, input_html: {value: f.object.tag_list.join(', ')} %>
  <%= error_span(@page[:tag_list]) %>

  <%= f.button :submit, :class => 'btn-primary' %>
  <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                admin_pages_path, :class => 'btn btn-default' %>
<% end %>

app/views/admin/pages/edit.html.erb
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => Page.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/admin/pages/index.html.erb
<div class="page-header">
  <h1><%=t '.title', :default => Page.model_name.human %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= Page.human_attribute_name(:id) %></th>
      <th><%= Page.human_attribute_name(:title) %></th>
      <th><%= Page.human_attribute_name(:slug) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @pages.each do |page| %>
      <tr>
        <td><%= link_to page.id, admin_page_path(page) %></td>
        <td><%= page.title %></td>
        <td><%= page.slug %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_admin_page_path(page), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      admin_page_path(page),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-default' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_admin_page_path,
            :class => 'btn btn-primary' %>

app/views/admin/pages/new.html.erb
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => Page.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/admin/pages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @page.title %>
</p>

<p>
  <strong>Slug:</strong>
  <%= @page.slug %>
</p>

<p>
  <strong>Content:</strong>
  <%= @page.content %>
</p>

<%= link_to 'Edit', edit_page_path(@page) %> |
<%= link_to 'Back', pages_path %>

app/views/contact_notifier/public_form.html.erb
<h1>Contato feito pelo site</h1>

<p>
  Uma mensagem foi enviada por <%= @contact.name %> (<%= @contact.email %>),
</p>

<pre>
<%= simple_format @contact.message %>
</pre>

app/views/contact_notifier/public_form.text.erb
ContactNotifier#public_form

<%= @greeting %>, find me in app/views/contact_notifier/public_form.text.erb

app/views/layouts/_menu_header.html.erb
<!-- nav and search start -->
<div class="nav-search-outer">
  <!-- nav start -->
  <nav class="navbar navbar-inverse" role="navigation">
    <div class="container">
      <div class="row">
        <div class="col-sm-16"> <a href="javascript:;" class="toggle-search pull-right"><span class="ion-ios7-search"></span></a>
          <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse"> <span class="sr-only">Toggle navigation</span> <span class="icon-bar"></span> <span class="icon-bar"></span> <span class="icon-bar"></span> </button>
          </div>
          <div class="collapse navbar-collapse" id="navbar-collapse">
            <ul class="nav navbar-nav text-uppercase main-nav ">
              <li><a href="<%= root_path %>">início</a></li>
              <% unless in_admin? %>
                <% site_menu_items.each do |menu_item| %>
                  <% if menu_item.children.blank? %>
                    <li><a href="<%= menu_item.link %>"><%= menu_item.title %></a></li>
                  <% else %>
                    <li class="dropdown"> <a href="javascript:void(0)" class="dropdown-toggle" data-toggle="dropdown"><%= menu_item.title %><span class="ion-ios7-arrow-down nav-icn"></span></a>
                      <ul class="dropdown-menu text-capitalize" role="menu">
                      <% menu_item.children.each do |menu_item_children| %>
                        <li><a href="<%= menu_item_children.link %>"><span class="ion-ios7-arrow-right nav-sub-icn"></span><%= menu_item_children.title %></a></li>
                      <% end -%>
                      </ul>
                    </li>
                  <% end -%>
                <% end -%>
              <% else %>
                <li class="dropdown"> <a href="javascript:void(0)" class="dropdown-toggle" data-toggle="dropdown">Administração<span class="ion-ios7-arrow-down nav-icn"></span></a>
                  <ul class="dropdown-menu text-capitalize" role="menu">
                    <li><a href="<%= admin_menu_items_path %>"><span class="ion-ios7-arrow-right nav-sub-icn"></span><%= MenuItem.model_name.human %></a></li>
                    <li><a href="<%= admin_pages_path %>"><span class="ion-ios7-arrow-right nav-sub-icn"></span><%= Page.model_name.human %></a></li>
                    <li><a href="<%= admin_news_categories_path %>"><span class="ion-ios7-arrow-right nav-sub-icn"></span><%= NewsCategory.model_name.human %></a></li>
                    <li><a href="<%= admin_news_index_path %>"><span class="ion-ios7-arrow-right nav-sub-icn"></span><%= News.model_name.human %></a></li>
                    <li><a href="<%= edit_admin_app_configuration_path(:prefeitura) %>"><span class="ion-ios7-arrow-right nav-sub-icn"></span><%= AppConfiguration.model_name.human %></a></li>
                  </ul>
                </li>
              <% end -%>
            </ul>
          </div>
        </div>
      </div>
    </div>
    <!-- nav end -->
    <!-- search start -->

    <div class="search-container ">
      <div class="container">
        <form action="" method="" role="search">
          <input id="search-bar" placeholder="buscar por..." autocomplete="off">
        </form>
      </div>
    </div>
    <!-- search end -->
  </nav>
  <!--nav end-->
</div>
<!-- nav and search end-->

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "PreControl" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
  </head>
  <body>

    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="<%= root_path %>">PreControl</a>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav">
            <li><%= link_to "Resumo de Operações", root_path  %></li>
            <li><%= link_to "Vendas", sales_path  %></li>
            <li><%= link_to "Tarefas na Rua", street_jobs_path  %></li>
            <li><%= link_to "Condicionais", pre_sales_path  %></li>
            <li><%= link_to "Recebimentos", daily_cashes_path  %></li>
            <li><%= link_to "Clientes", clients_path  %></li>
            <li><%= link_to "Produtos", products_path  %></li>
            <li><%= link_to "Minha Conta", edit_user_registration_path  %></li>
            <li><%= link_to('Sair', destroy_user_session_path, :method => :delete) %></li>
          </ul>
        </div>
      </div>
    </div>

    <div class="container" id="central-page">
      <div class="row">
        <div class="col-lg-12">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
      </div><!--/row-->

    </div> <!-- /container -->

    <div class="container">
      <footer>
        <p>&copy; PreControl 2014 - <%= Date.today.year %></p>
      </footer>
    </div>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>
    <%= app_configuration.company_name %> - <%= content_for?(:title) ? yield(:title) : "Principal" %>
    </title>
  <%= csrf_meta_tags %>
  <link rel="shortcut icon" href="/assets/site/favicon.ico" type="image/x-icon">
  <link rel="icon" href="/assets/site/favicon.ico" type="image/x-icon">
  <!-- bootstrap styles-->
  <%= stylesheet_link_tag "site", :media => "all" %>
  <!-- google font -->
  <link href='http://fonts.googleapis.com/css?family=Open+Sans:400,700,600,800' rel='stylesheet' type='text/css'>
  <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
  <!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
  <![endif]-->

</head>
<body>
  <!-- preloader start -->
  <div id="preloader">
    <div id="status"></div>
  </div>
  <!-- preloader end -->

  <!-- wrapper start -->
  <div class="wrapper">
    <!-- header toolbar start -->
    <div class="header-toolbar">
      <div class="container">
        <div class="row">
          <div class="col-md-16 text-uppercase">
            <div class="row">
              <div class="col-sm-8 col-xs-16">
                <ul id="inline-popups" class="list-inline">
                  <li class="hidden-xs"><a href="#">Portal da Transparência</a></li>
                  <li><a  href="<%= new_contact_path %>">Fale Conosco</a></li>
                  <li><a  href="<%= admin_root_path %>">Administração</a></li>
                </ul>
              </div>
              <div class="col-xs-16 col-sm-8">
                <div class="row">
                  <div id="weather" class="col-xs-16 col-sm-8 col-lg-9"></div>
                  <div id="time-date" class="col-xs-16 col-sm-8 col-lg-7"></div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <!-- header toolbar end -->

    <!-- sticky header start -->
    <div class="sticky-header">
      <!-- header start -->
      <div class="container header">
        <div class="row">
          <div class="col-sm-5 col-md-5 wow fadeInUpLeft animated"><a class="navbar-brand" href="<%= root_path %>"><%= app_configuration.company_name %></a></div>
          <div class="col-sm-11 col-md-11 hidden-xs text-right"><img src="/assets/site/ads/468-60-ad.gif" width="468" height="60" alt=""/></div>
        </div>
      </div>
      <!-- header end -->
      <%= render partial: "layouts/menu_header" %>
    </div>
    <!-- sticky header end -->

    <div class="container">
      <%= bootstrap_flash %>
      <%= yield %>
    </div>

    <!-- Footer start -->
    <footer>
      <div class="top-sec">
        <div class="container ">
          <div class="row match-height-container">
            <div class="col-sm-16 subscribe-info wow fadeInDown animated" data-wow-delay="1s" data-wow-offset="40">
              <div class="row">
                <div class="col-sm-16">
                  <div class="f-title"><%= t('app_title') %></div>
                  <%= simple_format app_configuration.definitions['bottom_slogan'] unless app_configuration.definitions.nil? %>
                </div>
                <div class="col-sm-16">
                  <div class="f-title">receba novidades por email</div>
                  <form class="form-inline">
                    <input type="email" class="form-control" id="input-email" placeholder="Digite seu endereço de e-mail">
                    <button type="submit" class="btn"> <span class="ion-paper-airplane text-danger"></span> </button>
                  </form>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="btm-sec">
        <div class="container">
          <div class="row">
            <div class="col-sm-16">
              <div class="row">
                <div class="col-sm-12 col-xs-16 f-nav wow fadeInDown animated" data-wow-delay="0.5s" data-wow-offset="10">
                  <ul class="list-inline ">
                    <li> <a href="<%= root_path %>"> Inicial</a></li>
                    <% site_menu_items.each do |menu_item| %>
                    <li><a href="<%= menu_item.first_link %>"><%= menu_item.title %></a></li>
                    <% end %>
                    <li> <a href="<%= new_contact_path %>">Contato</a></li>
                  </ul>
                </div>
                <div class="col-sm-4 col-xs-16 copyrights text-right wow fadeInDown animated" data-wow-delay="0.5s" data-wow-offset="10">© <%= Date.today.year %> <%= t('app_title') %> </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </footer>
    <!-- Footer end -->
  </div>
  <!-- wrapper end -->
  <%= javascript_include_tag "site" %>
</body>
</html>