config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  require 'sidekiq/web'
    mount Sidekiq::Web => '/sidekiq'
  devise_for :users

  root 'home#index'

  namespace :admin do
    root 'dashboard#index'
    resources :menu_items
    resources :pages
    resources :news_categories
    resources :news
    resources :app_configurations, only: [:edit, :update]
  end

  resources :pages, path: 'conteudo', only: :show
  resources :contacts, path: 'fale-conosco', only: [:new, :create]

end

app/models/news.rb
class News < ActiveRecord::Base
  extend FriendlyId
  acts_as_taggable
  attr_accessor :master_picture

  friendly_id :title, use: :slugged
  belongs_to :news_category
  has_many :pictures, as: :imageable, dependent: :destroy

  validates :title, :content, :resume, :news_category_id, presence: true

  scope :portal_transparencia, -> {joins(:news_category).where("news_categories.slug = ?", "portal-transparencia")}

  def picture
    @picture ||= begin
      pictures.where(master: true).first.try(:image)
    end
  end

  after_save do
    if self.master_picture
      Picture.transaction do
        self.pictures.update_all(master: false)
        self.pictures.build(master: true, image: self.master_picture).save!
      end
    end
  end
end

app/controllers/admin/news_controller.rb
class Admin::NewsController < ApplicationController
  before_action :set_news, only: [:show, :edit, :update, :destroy]

  # GET /news
  # GET /news.json
  def index
    @news = News.all
  end

  # GET /news/1
  # GET /news/1.json
  def show
  end

  # GET /news/new
  def new
    @news = News.new
  end

  # GET /news/1/edit
  def edit
  end

  # POST /news
  # POST /news.json
  def create
    @news = News.new(news_params)

    respond_to do |format|
      if @news.save
        format.html { redirect_to admin_news_index_path, notice: 'News was successfully created.' }
        format.json { render :show, status: :created, location: @news }
      else
        format.html { render :new }
        format.json { render json: @news.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /news/1
  # PATCH/PUT /news/1.json
  def update
    respond_to do |format|
      if @news.update(news_params)
        format.html { redirect_to admin_news_index_path, notice: 'News was successfully updated.' }
        format.json { render :show, status: :ok, location: @news }
      else
        format.html { render :edit }
        format.json { render json: @news.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /news/1
  # DELETE /news/1.json
  def destroy
    @news.destroy
    respond_to do |format|
      format.html { redirect_to admin_news_index_path, notice: 'News was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_news
      @news = News.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def news_params
      params.require(:news).permit(:news_category_id, :title, :slug, :resume, :content, :source, :tag_list, :created_at, :master_picture)
    end
end

app/helpers/news_helper.rb
module NewsHelper
end

app/views/admin/news/_form.html.erb
<%= simple_form_for [:admin, @news], wrapper: :vertical_input_group, :html => { :class => 'vertical-horizontal' } do |f| %>
  <%= f.error_notification %>

    <%= f.association :news_category %>
    <%= error_span(@news[:news_category]) %>
    <%= f.input :title %>
    <%= error_span(@news[:title]) %>
    <%= f.input :master_picture, as: :file %>
    <% if f.object.picture %>
    <div class="row form-group">
      <figure><%= image_tag f.object.picture.url(:big), class: "col-lg-6" %></figure>
    </div>
    <% end -%>
    <%= error_span(@news[:master_picture]) %>
    <%= f.input :resume, :as => :ckeditor %>
    <%= error_span(@news[:resume]) %>
    <%= f.input :content, :as => :ckeditor %>
    <%= error_span(@news[:content]) %>
    <%= f.input :source %>
    <%= error_span(@news[:source]) %>
    <%= f.input :created_at %>
    <%= error_span(@news[:created_at]) %>

  <%= f.button :submit, :class => 'btn-primary' %>
  <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                admin_news_index_path, :class => 'btn btn-default' %>
<% end %>

app/views/admin/news/edit.html.erb
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => News.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/admin/news/index.html.erb
<div class="page-header">
  <h1><%=t '.title', :default => News.model_name.human %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= News.human_attribute_name(:id) %></th>
      <th><%= News.human_attribute_name(:title) %></th>
      <th><%= News.human_attribute_name(:slug) %></th>
      <th><%= News.human_attribute_name(:news_category_id) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @news.each do |news| %>
      <tr>
        <td><%= link_to news.id, admin_news_path(news) %></td>
        <td><%= news.title %></td>
        <td><%= news.slug %></td>
        <td><%= news.news_category.try(:name) %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_admin_news_path(news), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      admin_news_path(news),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-default' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_admin_news_path,
            :class => 'btn btn-primary' %>

app/views/admin/news/new.html.erb
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => News.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/admin/news/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>News category:</strong>
  <%= @news.news_category %>
</p>

<p>
  <strong>Title:</strong>
  <%= @news.title %>
</p>

<p>
  <strong>Slug:</strong>
  <%= @news.slug %>
</p>

<p>
  <strong>Resume:</strong>
  <%= @news.resume %>
</p>

<p>
  <strong>Content:</strong>
  <%= @news.content %>
</p>

<p>
  <strong>Source:</strong>
  <%= @news.source %>
</p>

<%= link_to 'Edit', edit_news_path(@news) %> |
<%= link_to 'Back', news_index_path %>