config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  require 'sidekiq/web'
    mount Sidekiq::Web => '/sidekiq'
  devise_for :users

  root 'home#index'

  namespace :admin do
    root 'dashboard#index'
    resources :menu_items
    resources :pages
    resources :news_categories
    resources :news
    resources :app_configurations, only: [:edit, :update]
  end

  resources :pages, path: 'conteudo', only: :show
  resources :contacts, path: 'fale-conosco', only: [:new, :create]

end

app/models/news_category.rb
class NewsCategory < ActiveRecord::Base
  extend FriendlyId
  friendly_id :name, use: :slugged
  validates :name, presence: true
  has_many :news, dependent: :destroy
end

app/controllers/admin/news_categories_controller.rb
class Admin::NewsCategoriesController < ApplicationController
  before_action :set_news_category, only: [:show, :edit, :update, :destroy]

  # GET /news_categories
  # GET /news_categories.json
  def index
    @news_categories = NewsCategory.all
  end

  # GET /news_categories/1
  # GET /news_categories/1.json
  def show
  end

  # GET /news_categories/new
  def new
    @news_category = NewsCategory.new
  end

  # GET /news_categories/1/edit
  def edit
  end

  # POST /news_categories
  # POST /news_categories.json
  def create
    @news_category = NewsCategory.new(news_category_params)

    respond_to do |format|
      if @news_category.save
        format.html { redirect_to admin_news_categories_path, notice: 'News category was successfully created.' }
        format.json { render :show, status: :created, location: @news_category }
      else
        format.html { render :new }
        format.json { render json: @news_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /news_categories/1
  # PATCH/PUT /news_categories/1.json
  def update
    respond_to do |format|
      if @news_category.update(news_category_params)
        format.html { redirect_to admin_news_categories_path, notice: 'News category was successfully updated.' }
        format.json { render :show, status: :ok, location: @news_category }
      else
        format.html { render :edit }
        format.json { render json: @news_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /news_categories/1
  # DELETE /news_categories/1.json
  def destroy
    @news_category.destroy
    respond_to do |format|
      format.html { redirect_to admin_news_categories_path, notice: 'News category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_news_category
      @news_category = NewsCategory.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def news_category_params
      params.require(:news_category).permit(:name, :slug)
    end
end

app/helpers/news_categories_helper.rb
module NewsCategoriesHelper
end

app/views/admin/news_categories/_form.html.erb
<%= simple_form_for [:admin, @news_category], wrapper: :vertical_input_group, :html => { :class => 'vertical-horizontal' } do |f| %>
  <%= f.error_notification %>

  <%= f.input :name %>
  <%= error_span(@news_category[:name]) %>

  <%= f.button :submit, :class => 'btn-primary' %>
  <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                admin_news_categories_path, :class => 'btn btn-default' %>
<% end %>

app/views/admin/news_categories/edit.html.erb
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => NewsCategory.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/admin/news_categories/index.html.erb
<div class="page-header">
  <h1><%=t '.title', :default => NewsCategory.model_name.human %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= NewsCategory.human_attribute_name(:id) %></th>
      <th><%= NewsCategory.human_attribute_name(:name) %></th>
      <th><%= NewsCategory.human_attribute_name(:slug) %></th>
      <th><%= NewsCategory.human_attribute_name(:news_count) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @news_categories.each do |news_category| %>
      <tr>
        <td><%= link_to news_category.id, admin_news_category_path(news_category) %></td>
        <td><%= news_category.name %></td>
        <td><%= news_category.slug %></td>
        <td><%= news_category.news.count %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_admin_news_category_path(news_category), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      admin_news_category_path(news_category),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-default' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_admin_news_category_path,
            :class => 'btn btn-primary' %>

app/views/admin/news_categories/new.html.erb
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => NewsCategory.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/admin/news_categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @news_category.name %>
</p>

<p>
  <strong>Slug:</strong>
  <%= @news_category.slug %>
</p>

<%= link_to 'Edit', edit_news_category_path(@news_category) %> |
<%= link_to 'Back', news_categories_path %>