config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  require 'sidekiq/web'
    mount Sidekiq::Web => '/sidekiq'
  devise_for :users

  root 'home#index'

  namespace :admin do
    root 'dashboard#index'
    resources :menu_items
    resources :pages
    resources :news_categories
    resources :news
    resources :app_configurations, only: [:edit, :update]
  end

  resources :pages, path: 'conteudo', only: :show
  resources :contacts, path: 'fale-conosco', only: [:new, :create]

end

app/models/contact.rb
class Contact < ActiveRecord::Base
  validates :name, :email, :message, presence: true
  after_create do
    ContactJob.perform_later self
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController

  # GET /contacts/new
  def new
    @contact = Contact.new
  end

  # POST /contacts
  # POST /contacts.json
  def create
    @contact = Contact.new(contact_params)

    respond_to do |format|
      if @contact.save
        format.html { redirect_to root_path, notice: 'Contato feito com sucesso.' }
        format.json { render :show, status: :created, location: @contact }
      else
        format.html { render :new }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  private

    # Never trust parameters from the scary internet, only allow the white list through.
    def contact_params
      params.require(:contact).permit(:name, :email, :message)
    end
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/views/contacts/_form.html.erb
<%= simple_form_for(@contact, html: {class: 'comment-form'}) do |f| %>
  <%= f.error_notification %>

  <div class="row">
    <div class="form-group col-xs-16 col-sm-16 name-field">
      <%= f.input :name, placeholder: "Nome*", class: 'form-control', required: :required %>
      <%= error_span(@contact[:name]) %>
    </div>

    <div class="form-group col-xs-16 col-sm-16 email-field">
      <%= f.input :email, type: :email, placeholder: "Email*", class: 'form-control', required: :required %>
      <%= error_span(@contact[:email]) %>
    </div>

    <div class="form-group col-xs-16 col-sm-16">
      <%= f.input :message, placeholder: "Sua mensagem*", class: 'form-control', required: :required, input_html: {rows: 8} %>
      <%= error_span(@contact[:message]) %>
    </div>
  </div>

  <div class="form-group">
    <%= f.button :submit, class: 'btn btn-danger', value: 'Enviar Mensagem' %>
  </div>
<% end %>

app/views/contacts/edit.html.erb
<h1>Editing Contact</h1>

<%= render 'form' %>

<%= link_to 'Show', @contact %> |
<%= link_to 'Back', contacts_path %>

app/views/contacts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Contacts</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Message</th>
      <th>Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @contacts.each do |contact| %>
      <tr>
        <td><%= contact.name %></td>
        <td><%= contact.email %></td>
        <td><%= contact.message %></td>
        <td><%= contact.status %></td>
        <td><%= link_to 'Show', contact %></td>
        <td><%= link_to 'Edit', edit_contact_path(contact) %></td>
        <td><%= link_to 'Destroy', contact, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Contact', new_contact_path %>

app/views/contacts/new.html.erb
<section>
    <div class="container ">
      <div class="row ">
        <!-- left sec Start -->
        <div class="col-sm-16">
          <div class="row">
            <div id="map_canvas" class="col-sm-16">
              <script type="text/javascript" src="http://maps.google.com/maps/api/js?sensor=false"></script>
              <div style="overflow:hidden;height:400px;width:100%;">
                <div id="gmap_canvas" style="height:400px;width:100%;"></div>
                <a class="google-map-code" href="http://www.trivoo.net/gutscheine/sheego/" id="get-map-data">trivoo</a></div>
              <script type="text/javascript"> function init_map(){var myOptions = {zoom:16,center:new google.maps.LatLng(-19.59473, -41.96981),mapTypeId: google.maps.MapTypeId.ROADMAP};map = new google.maps.Map(document.getElementById("gmap_canvas"), myOptions);marker = new google.maps.Marker({map: map,position: new google.maps.LatLng(-19.59473, -41.96981)});infowindow = new google.maps.InfoWindow({content:"<b>Egypt</b><br/><br/> Cairo" });google.maps.event.addListener(marker, "click", function(){infowindow.open(map,marker);});}google.maps.event.addDomListener(window, 'load', init_map);</script>
            </div>
            <div class="col-sm-16">
              <div class="row">
                <div class="main-title-outer pull-left">
                  <div class="main-title">Fale Conosco</div>
                </div>
                <div class="col-sm-11">
                  <%= render 'form' %>
                </div>
                <div class="col-sm-4  adress">
                  <address>
                  <strong>Endereço</strong><br>
                  <%= simple_format app_configuration.definitions['address'] unless app_configuration.definitions.nil? %>
                  <%= simple_format app_configuration.definitions['phone'] unless app_configuration.definitions.nil? %>
                  </address>
                  <address>
                  <strong>Advertising mail</strong><br>
                  <%= mail_to app_configuration.definitions['email'] unless app_configuration.definitions.nil? %>
                  </address>
                  <strong>Social</strong><br>
                  <ul class="list-inline">
                    <li><a href="#"><span class="ion-social-twitter"></span></a></li>
                    <li><a href="#"><span class="ion-social-facebook"></span></a></li>
                    <li><a href="#"><span class="ion-social-googleplus"></span></a></li>
                  </ul>
                </div>
              </div>
            </div>
          </div>
        </div>
        <!-- left sec End -->

      </div>
    </div>
  </section>

app/views/contacts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @contact.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @contact.email %>
</p>

<p>
  <strong>Message:</strong>
  <%= @contact.message %>
</p>

<p>
  <strong>Status:</strong>
  <%= @contact.status %>
</p>

<%= link_to 'Edit', edit_contact_path(@contact) %> |
<%= link_to 'Back', contacts_path %>